/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlackjackRouteImport } from './routes/blackjack'
import { Route as CoinflipRouteImport } from './routes/coinflip'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as DiceRouteImport } from './routes/dice'
import { Route as MinesRouteImport } from './routes/mines'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiPublicBotPaymentReceivedRouteImport } from './routes/api/public/bot/payment-received'
import { Route as ApiPublicBotPendingRouteImport } from './routes/api/public/bot/pending'
import { Route as ApiPublicBotWithdrawalCompleteRouteImport } from './routes/api/public/bot/withdrawal-complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackRoute = BlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinflipRoute = CoinflipRouteImport.update({
  id: '/coinflip',
  path: '/coinflip',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const DiceRoute = DiceRouteImport.update({
  id: '/dice',
  path: '/dice',
  getParentRoute: () => rootRouteImport,
} as any)
const MinesRoute = MinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotPaymentReceivedRoute =
  ApiPublicBotPaymentReceivedRouteImport.update({
    id: '/api/public/bot/payment-received',
    path: '/api/public/bot/payment-received',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotPendingRoute = ApiPublicBotPendingRouteImport.update({
  id: '/api/public/bot/pending',
  path: '/api/public/bot/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotWithdrawalCompleteRoute =
  ApiPublicBotWithdrawalCompleteRouteImport.update({
    id: '/api/public/bot/withdrawal-complete',
    path: '/api/public/bot/withdrawal-complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/coinflip': typeof CoinflipRoute
  '/crash': typeof CrashRoute
  '/dice': typeof DiceRoute
  '/mines': typeof MinesRoute
  '/wallet': typeof WalletRoute
  '/api/public/bot/payment-received': typeof ApiPublicBotPaymentReceivedRoute
  '/api/public/bot/pending': typeof ApiPublicBotPendingRoute
  '/api/public/bot/withdrawal-complete': typeof ApiPublicBotWithdrawalCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/coinflip': typeof CoinflipRoute
  '/crash': typeof CrashRoute
  '/dice': typeof DiceRoute
  '/mines': typeof MinesRoute
  '/wallet': typeof WalletRoute
  '/api/public/bot/payment-received': typeof ApiPublicBotPaymentReceivedRoute
  '/api/public/bot/pending': typeof ApiPublicBotPendingRoute
  '/api/public/bot/withdrawal-complete': typeof ApiPublicBotWithdrawalCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/coinflip': typeof CoinflipRoute
  '/crash': typeof CrashRoute
  '/dice': typeof DiceRoute
  '/mines': typeof MinesRoute
  '/wallet': typeof WalletRoute
  '/api/public/bot/payment-received': typeof ApiPublicBotPaymentReceivedRoute
  '/api/public/bot/pending': typeof ApiPublicBotPendingRoute
  '/api/public/bot/withdrawal-complete': typeof ApiPublicBotWithdrawalCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blackjack'
    | '/coinflip'
    | '/crash'
    | '/dice'
    | '/mines'
    | '/wallet'
    | '/api/public/bot/payment-received'
    | '/api/public/bot/pending'
    | '/api/public/bot/withdrawal-complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blackjack'
    | '/coinflip'
    | '/crash'
    | '/dice'
    | '/mines'
    | '/wallet'
    | '/api/public/bot/payment-received'
    | '/api/public/bot/pending'
    | '/api/public/bot/withdrawal-complete'
  id:
    | '__root__'
    | '/'
    | '/blackjack'
    | '/coinflip'
    | '/crash'
    | '/dice'
    | '/mines'
    | '/wallet'
    | '/api/public/bot/payment-received'
    | '/api/public/bot/pending'
    | '/api/public/bot/withdrawal-complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlackjackRoute: typeof BlackjackRoute
  CoinflipRoute: typeof CoinflipRoute
  CrashRoute: typeof CrashRoute
  DiceRoute: typeof DiceRoute
  MinesRoute: typeof MinesRoute
  WalletRoute: typeof WalletRoute
  ApiPublicBotPaymentReceivedRoute: typeof ApiPublicBotPaymentReceivedRoute
  ApiPublicBotPendingRoute: typeof ApiPublicBotPendingRoute
  ApiPublicBotWithdrawalCompleteRoute: typeof ApiPublicBotWithdrawalCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack': {
      id: '/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof BlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coinflip': {
      id: '/coinflip'
      path: '/coinflip'
      fullPath: '/coinflip'
      preLoaderRoute: typeof CoinflipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice': {
      id: '/dice'
      path: '/dice'
      fullPath: '/dice'
      preLoaderRoute: typeof DiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mines': {
      id: '/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof MinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/payment-received': {
      id: '/api/public/bot/payment-received'
      path: '/api/public/bot/payment-received'
      fullPath: '/api/public/bot/payment-received'
      preLoaderRoute: typeof ApiPublicBotPaymentReceivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/pending': {
      id: '/api/public/bot/pending'
      path: '/api/public/bot/pending'
      fullPath: '/api/public/bot/pending'
      preLoaderRoute: typeof ApiPublicBotPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/withdrawal-complete': {
      id: '/api/public/bot/withdrawal-complete'
      path: '/api/public/bot/withdrawal-complete'
      fullPath: '/api/public/bot/withdrawal-complete'
      preLoaderRoute: typeof ApiPublicBotWithdrawalCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlackjackRoute: BlackjackRoute,
  CoinflipRoute: CoinflipRoute,
  CrashRoute: CrashRoute,
  DiceRoute: DiceRoute,
  MinesRoute: MinesRoute,
  WalletRoute: WalletRoute,
  ApiPublicBotPaymentReceivedRoute: ApiPublicBotPaymentReceivedRoute,
  ApiPublicBotPendingRoute: ApiPublicBotPendingRoute,
  ApiPublicBotWithdrawalCompleteRoute: ApiPublicBotWithdrawalCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
